spring.application.name=asignacion turnos Enfermeria
spring.datasource.url=***REMOVED***
spring.datasource.username=***REMOVED***
spring.datasource.password=***REMOVED***
spring.datasource.driver-class-name=org.***REMOVED***ql.Driver
spring.jpa.database-platform=***REMOVED***
spring.jpa.hibernate.ddl-auto=***REMOVED***
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.security.user.name=***REMOVED***
spring.security.user.password=***REMOVED***
spring.jpa.open-in-view=false
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.pool-name=HikariPool-1

springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.doc-expansion=none